# Generated by Django 5.1.2 on 2024-11-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nadlezna',
            fields=[
                ('isAdmin', models.BooleanField(default=False)),
                ('sifNadlezna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nadlezna_osoba', serialize=False, to='api.osoba')),
            ],
        ),
        migrations.AlterField(
            model_name='susjed',
            name='sifSusjed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='susjed_osoba', serialize=False, to='api.osoba'),
        ),
    ]
