# Generated by Django 5.1.3 on 2024-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_susjed_sifsusjed_alter_nadlezna_sifnadlezna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='susjed',
            name='ocjena',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tvrtka',
            name='ocjena',
            field=models.FloatField(default=0.0),
        ),
    ]
