# Generated by Django 5.1.2 on 2024-11-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nadlezna_alter_susjed_sifsusjed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadZadano', models.IntegerField()),
                ('datumDogadaj', models.DateField()),
                ('vrijemeDogadaj', models.TimeField()),
                ('nazivDogadaj', models.CharField(max_length=255)),
                ('adresaDogadaj', models.CharField(max_length=255)),
                ('statusDogadaj', models.CharField(max_length=255)),
                ('vrstaDogadaj', models.CharField(max_length=255)),
                ('opisDogadaj', models.CharField(max_length=2047, null=True)),
                ('nagradaBod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VrstaUsluga',
            fields=[
                ('sifVrsta', models.IntegerField(primary_key=True, serialize=False)),
                ('nazivVrsta', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='osoba',
            name='ime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='prezime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='susjed',
            name='bodovi',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='susjed',
            name='kvartSusjed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='susjed',
            name='mjestoSusjed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='susjed',
            name='opisSusjed',
            field=models.CharField(max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='tvrtka',
            name='adresaTvrtka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvrtka',
            name='kvartTvrtka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvrtka',
            name='mjestoTvrtka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvrtka',
            name='nazivTvrtka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvrtka',
            name='opisTvrtka',
            field=models.CharField(max_length=4095, null=True),
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('sifKom', models.AutoField(primary_key=True, serialize=False)),
                ('textKom', models.CharField(max_length=2047)),
                ('sifDaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dogadaj')),
                ('sifPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dogadaj',
            name='sifVolonter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.komentar'),
        ),
        migrations.CreateModel(
            name='Prihvaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjenaPonuda', models.IntegerField()),
                ('kadZadano', models.DateTimeField()),
                ('sifSusjed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.susjed')),
                ('sifTvrtka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tvrtka')),
            ],
        ),
        migrations.CreateModel(
            name='PrijavljenNa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNagraden', models.BooleanField(default=False)),
                ('kadZadano', models.IntegerField()),
                ('sifVolonter', models.IntegerField()),
                ('sifSusjed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.susjed')),
            ],
        ),
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadZadano', models.DateTimeField()),
                ('cijenaNovac', models.FloatField(blank=True, null=True)),
                ('nazivPonuda', models.CharField(max_length=255)),
                ('isAktivna', models.BooleanField()),
                ('opisPonuda', models.CharField(blank=True, max_length=2048, null=True)),
                ('sifTvrtka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tvrtka')),
                ('sifVrsta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vrstausluga')),
            ],
        ),
        migrations.CreateModel(
            name='JeSposoban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifSusjed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.susjed')),
                ('sifVrsta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vrstausluga')),
            ],
        ),
        migrations.CreateModel(
            name='Zahtjev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijenaBod', models.IntegerField()),
                ('kadZadan', models.DateTimeField()),
                ('nazivZahtjev', models.CharField(max_length=255)),
                ('adresaZahtjev', models.CharField(max_length=255)),
                ('statusZahtjev', models.CharField(max_length=255)),
                ('opisZahtjev', models.CharField(max_length=2047, null=True)),
                ('ocjenaIzvrsitelj', models.IntegerField(blank=True, null=True)),
                ('sifIzvrsitelj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='izvrsitelj_set', to='api.susjed')),
                ('sifSusjed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.susjed')),
                ('sifVrsta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vrstausluga')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dogadaj',
            constraint=models.UniqueConstraint(fields=('sifVolonter', 'kadZadano'), name='unique_volonter_event'),
        ),
        migrations.AddConstraint(
            model_name='prijavljenna',
            constraint=models.UniqueConstraint(fields=('sifSusjed', 'kadZadano', 'sifVolonter'), name='unique_prijavljen_na'),
        ),
        migrations.AddConstraint(
            model_name='ponuda',
            constraint=models.UniqueConstraint(fields=('kadZadano', 'sifTvrtka'), name='unique_kadZadano_sifTvrtka'),
        ),
        migrations.AddConstraint(
            model_name='jesposoban',
            constraint=models.UniqueConstraint(fields=('sifSusjed', 'sifVrsta'), name='unique_susjed_vrsta'),
        ),
        migrations.AddConstraint(
            model_name='zahtjev',
            constraint=models.UniqueConstraint(fields=('kadZadan', 'sifSusjed'), name='unique_kadZadan_sifSusjed'),
        ),
    ]
