# Generated by Django 5.1.3 on 2025-01-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_susjed_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadaj',
            name='sifVolonter',
            field=models.IntegerField(),
        ),
    ]
