# Generated by Django 5.1.3 on 2025-01-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dogadaj_sifvolonter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadaj',
            name='kadZadano',
            field=models.CharField(max_length=255),
        ),
    ]
