# Generated by Django 5.1.4 on 2025-01-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dogadaj_kadzadano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='sifDaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='sifPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tvrtka'),
        ),
    ]
