# Generated by Django 5.1.3 on 2025-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_susjed_brojocjena_alter_susjed_zbrojocjena_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zahtjev",
            name="unique_kadZadan_sifSusjed",
        ),
        migrations.RemoveField(
            model_name="zahtjev",
            name="kadZadan",
        ),
        migrations.RemoveField(
            model_name="zahtjev",
            name="ocjenaIzvrsitelj",
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="sifVrsta",
            field=models.TextField(default=""),
        ),
        migrations.AddConstraint(
            model_name="zahtjev",
            constraint=models.UniqueConstraint(
                fields=("sifSusjed",), name="unique_kadZadan_sifSusjed"
            ),
        ),
    ]
