# Generated by Django 5.1.4 on 2025-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_korisnik_ismoderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponuda',
            name='sifVrsta',
            field=models.TextField(default=''),
        ),
    ]
