# Generated by Django 5.1.4 on 2025-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ponuda_sifvrsta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponuda',
            name='kadZadano',
            field=models.CharField(max_length=255),
        ),
    ]
