# Generated by Django 5.1.3 on 2025-01-19 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_ponuda_kadzadano"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zahtjev",
            name="unique_kadZadan_sifSusjed",
        ),
        migrations.AlterField(
            model_name="nadlezna",
            name="sifNadlezna",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="nadlezna_account",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="susjed",
            name="sifSusjed",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="susjed_account",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tvrtka",
            name="sifTvrtka",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="tvrtka_account",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="prihvaca",
            constraint=models.UniqueConstraint(
                fields=("sifSusjed", "kadZadano", "sifTvrtka"),
                name="unique_susjed_kadZadano_tvrtka",
            ),
        ),
        migrations.AddConstraint(
            model_name="zahtjev",
            constraint=models.UniqueConstraint(
                fields=("sifSusjed",), name="izvornik_unique_kadZadan_sifSusjed"
            ),
        ),
    ]
