# Generated by Django 5.1.3 on 2025-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_zahtjev_izvornik_unique_kadzadan_sifsusjed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zahtjev",
            name="sifIzvrsitelj",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="sifSusjed",
            field=models.IntegerField(),
        ),
    ]
